"""
Remove non-Turkish / junk given names from data/name_pools/country_TUR.json.

Keeps Turkish (and common Turkish-citizen Persian/Arabic/Kurdish) spellings; drops:
- Western / Slavic / global football imports
- Arabic/English transliterations that duplicate Turkish forms (Mohamed vs Mehmet)
- Place names and obvious dataset junk (professions, slurs, fragments)
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TUR_PATH = ROOT / "data" / "name_pools" / "country_TUR.json"

# Whole-token matches only (hyphenated compounds are one token).
NON_TURKISH_OR_JUNK_GIVEN: frozenset[str] = frozenset(
    {
        # Western / global given names (incl. common dual-national football imports)
        "John",
        "Johnny",
        "Jack",
        "James",
        "Jason",
        "Jordan",
        "Jeremy",
        "Jamie",
        "Jay",
        "Jake",
        "Josh",
        "Jonathan",
        "Joseph",
        "Joe",
        "Joel",
        "Jonas",
        "Julian",
        "David",
        "Daniel",
        "Danny",
        "Dan",
        "Dave",
        "Douglas",
        "Dean",
        "Dennis",
        "Derek",
        "Michael",
        "Matthew",
        "Matt",
        "Marc",
        "Mark",
        "Mike",
        "Martin",
        "Marcel",
        "Marcus",
        "Mario",
        "Marko",
        "Thomas",
        "Tim",
        "Timothy",
        "Tom",
        "Tommy",
        "Tyler",
        "Tony",
        "Terry",
        "Travis",
        "Trevor",
        "Troy",
        "Tracy",
        "Alex",
        "Alexander",
        "Andy",
        "Andrew",
        "Anthony",
        "Adrian",
        "Albert",
        "Aaron",
        "Robert",
        "Richard",
        "Roy",
        "Raymond",
        "Ryan",
        "Rob",
        "Roger",
        "Ronald",
        "Ross",
        "Russell",
        "Paul",
        "Peter",
        "Patrick",
        "Philip",
        "Phillip",
        "Perry",
        "Pete",
        "Chris",
        "Christopher",
        "Christian",
        "Charles",
        "Steve",
        "Steven",
        "Stephen",
        "Scott",
        "Sean",
        "Simon",
        "Seth",
        "Shane",
        "Shaun",
        "Sidney",
        "Stanley",
        "Stuart",
        "Sunny",
        "Sam",
        "Samuel",
        "Kevin",
        "Keith",
        "Kyle",
        "Ken",
        "Kenneth",
        "Gary",
        "George",
        "Gabriel",
        "Greg",
        "Gregory",
        "Grant",
        "William",
        "Will",
        "Walter",
        "Wayne",
        "Wesley",
        "Wade",
        "Warren",
        "Wilson",
        "Henry",
        "Harry",
        "Hank",
        "Howard",
        "Harold",
        "Frank",
        "Fred",
        "Frederick",
        "Franklin",
        "Eric",
        "Edward",
        "Edwin",
        "Eddie",
        "Ethan",
        "Evan",
        "Ivan",
        "Ian",
        "Isaac",
        "Irving",
        "Igor",
        "Vladimir",
        "Vlad",
        "Viktor",
        "Victor",
        "Vincent",
        "Vadim",
        "Artem",
        "Maksim",
        "Marat",
        "Ruslan",
        "Roman",
        "Leo",
        "Leon",
        "Lucas",
        "Luke",
        "Louis",
        "Leonardo",
        "Luis",
        "Diego",
        "Dennis",
        "Carl",
        "Craig",
        "Curtis",
        "Nick",
        "Nathan",
        "Neil",
        "Nelson",
        "Nicholas",
        "Oscar",
        "Oliver",
        "Owen",
        "Jeff",
        "Jeffrey",
        "Jim",
        "Justin",
        "Jon",
        "Jorge",
        "Jose",
        "Juan",
        "Joao",
        "Bob",
        "Bill",
        "Brian",
        "Bruce",
        "Ben",
        "Benjamin",
        "Bryan",
        "Charlie",
        "Chuck",
        "Rick",
        "Ricky",
        "Ray",
        "Randy",
        "Ralph",
        "Randall",
        "Reginald",
        "Rex",
        "Rodney",
        "Larry",
        "Lawrence",
        "Lee",
        "Leonard",
        "Lewis",
        "Lloyd",
        "Zach",
        "Zachary",
        "Zeeshan",
        "Shawn",
        "Prince",
        "King",
        # Arabic / English spellings not primary in Turkish orthography
        "Mohamed",
        "Mohammad",
        "Mohammed",
        "Mohamad",
        "Muhammad",
        "Mohd",
        "Ahmad",
        "Ahmed",
        "Mahmoud",
        "Hassan",
        "Hussein",
        "Hussain",
        "Osama",
        "Omar",
        "Yousef",
        "Usman",
        "Sayed",
        "Waseem",
        "Hamed",
        "Abdulla",
        "Yusif",
        "Mamed",
        "Khayal",
        "Umair",
        "Nicat",
        "Rufat",
        "Vugar",
        "Elmar",
        "Elman",
        "Elmir",
        "Aksel",
        "Bek",
        "Abdullah-Al",
        "Abdul",
        # Junk / fragments / professions / slurs / chat tokens
        "By",
        "Tc",
        "Ve",
        "Ne",
        "Bi",
        "Ya",
        "Ha",
        "Om",
        "Lut",
        "Al",
        "Abu",
        "Ebu",
        "Just",
        "Doktor",
        "Ogretmen",
        "Muhendis",
        "Sosyal",
        "Isimsiz",
        "Memo",
        "Ibo",
        "Apo",
        "Kral",
        "Milli",
        "Başkan",
        "Siyasi",
        "Demokrat",
        "Kemalist",
        "Egitim",
        "Hekim",
        "Ayı",
        "Deli",
        "Bay",
        "Zenci",
        "Zevk",
        "Karizma",
        "Laik",
        "Muzik",
        "Maco",
        "Muro",
        "Neco",
        "Reel",
        "Kotu",
        "Hebun",
        "Hak",
        "Zor",
        "Usta",
        "Özel",
        "Kultur",
        "Özenç",
        "Borsa",
        "Kültür",
        # Place / region nicknames mis-ingested as given names
        "Samsun",
        "Samsunlu",
        "Denizli",
        "Mersin",
        "Tekirdag",
        "Izmit",
        "Izmirli",
        "Konyali",
        "Antepli",
        "Hatay",
        "Bolu",
        "Çorum",
        "Kars",
        "Karaman",
        "Ordu",
        "Sivas",
        "Tokat",
        "Sakarya",
        "Angara",
        "Yemen",
        "Arap",
        "Adıyaman",
        "Bartin",
        "Gediz",
        "Balkan",
        "Karadeniz",
        "Kafkas",
    }
)


def cleanse() -> dict:
    with open(TUR_PATH, encoding="utf-8") as f:
        data = json.load(f)

    removed: list[str] = []
    for tier in ("very_common", "common", "mid", "rare"):
        kept: list[str] = []
        for name in data["given_names_male"][tier]:
            if name in NON_TURKISH_OR_JUNK_GIVEN:
                removed.append(name)
            else:
                kept.append(name)
        data["given_names_male"][tier] = kept

    return {"data": data, "removed": removed, "removed_count": len(removed)}


def main() -> None:
    result = cleanse()
    data = result["data"]
    removed = result["removed"]
    with open(TUR_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Removed {result['removed_count']} given names (non-Turkish / junk).")
    uniq = sorted(set(removed))
    print(f"Unique removed: {len(uniq)}")
    for tier in ("very_common", "common", "mid", "rare"):
        n = len(data["given_names_male"][tier])
        print(f"  {tier}: {n} male given")

    if uniq:
        print("Removed tokens:", ", ".join(uniq[:80]))
        if len(uniq) > 80:
            print(f"  ... +{len(uniq) - 80} more")


if __name__ == "__main__":
    main()
